import Head from 'next/head'
import styles from '../../styles/Home.module.css'

export async function getServerSideProps({ params }) {

    const { job } = params;

    try{
        const res = await fetch(`https://f81l2jaz49.execute-api.us-east-1.amazonaws.com/dev/todos/${job}`)
        const data = await res.json()
    
        if (!data || data.message || data.private ) {
            return {
                notFound: true,
            }
        }
    
        return {
            props: { data }, // will be passed to the page component as props
        }
    }catch(e){
        return {
            notFound: true,
        }
    }

}

export default function JobPostSSR({ data }) {

    console.log(data)

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    SSR Page Launch - {data.id}
                </h1>
                <p>
                    {data.CEO}
                </p>
            </main>
        </div>
    )
}
