import Head from 'next/head'
import styles from '../styles/Home.module.css'

// This function gets called at build time
export async function getStaticPaths() {
    const res = await fetch(`https://f81l2jaz49.execute-api.us-east-1.amazonaws.com/dev/todos`)
    const data = await res.json()
  
    const paths = data.map((company) => ({
      params: { launch: company.id },
    }))
  
    // We'll pre-render only these paths at build time.
    // { fallback: false } means other routes should 404.
    return { paths, fallback: false }
  }

export async function getStaticProps({params}) {
    const res = await fetch(`https://f81l2jaz49.execute-api.us-east-1.amazonaws.com/dev/todos/${params.launch}`)
    const data = await res.json()

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: { data }, // will be passed to the page component as props
  }
}

export default function Launch({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Static Generated Launch - {data.id}
        </h1>
        <p>
            {data.CEO}
        </p>
      </main>
    </div>
  )
}
