import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export async function getStaticProps(context) {
  const res = await fetch(`https://f81l2jaz49.execute-api.us-east-1.amazonaws.com/dev/todos`)
  const data = await res.json()

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: { data }, // will be passed to the page component as props
  }
}

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Sashrika Nextjs
        </h1>

        <p className={styles.description}>
          Below are static generated pages
        </p> 
        {
          data.map(path => (
            <Link key={path.id+"ssg"} href={`/${path.id}`}>
              <a>{path.id}</a>
            </Link>
          ))
        }

        <p className={styles.description}>
          Below are server side rendered pages
        </p>
        {
          data.map(path => (
            <Link key={path.id+"ssr"} href={`/ssr/${path.id}`}>
              <a>{path.id} {(path.id === "aws" ? " -> You can try private field here" : "")} </a>
            </Link>
          ))
        }
      </main>
    </div>
  )
}
