import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export async function getStaticProps(context) {

    const array = ["aws", "facebook", "opensea", "coinbase", "tesla", "twitter", "netflix", "google", "paypal", "spacex"]

    const promises = array.map(item => fetch(`https://f81l2jaz49.execute-api.us-east-1.amazonaws.com/dev/todos/${item}`))

    const res = await Promise.all(promises);

    const jsonresPromises = res.map(ress => ress.json())

    const data = await Promise.all(jsonresPromises)

    //   if (!data) {
    //     return {
    //       notFound: true,
    //     }
    //   }

    return {
        props: { data }, // will be passed to the page component as props
    }
}

export default function Parallel({ data }) {

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome Parallel SSR
                </h1>

                {
                    data.map(path => (
                        <li key={"ssrparalel" + path.id}>
                            {path.id}
                        </li>
                    ))
                }

            </main>
        </div>
    )
}
