import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export async function getServerSideProps(context) {

    const res1 = await fetch(`https://f81l2jaz49.execute-api.us-east-1.amazonaws.com/dev/todos/aws`)
    const data1 = await res1.json()

    const res3 = await fetch(`https://f81l2jaz49.execute-api.us-east-1.amazonaws.com/dev/todos/tesla`)
    const data2 = await res3.json()

    const res4 = await fetch(`https://f81l2jaz49.execute-api.us-east-1.amazonaws.com/dev/todos/netflix`)
    const data3 = await res4.json()

    const res5 = await fetch(`https://f81l2jaz49.execute-api.us-east-1.amazonaws.com/dev/todos/facebook`)
    const data4 = await res5.json()

    return {
        props: { data1, data2, data3, data4 }, // will be passed to the page component as props
    }
}

export default function Sequentiol({ data1, data2, data3, data4 }) {

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome Sequestion API calls
                </h1>

                {
                    [data1, data2, data3, data4].map(p => ({id: p.id})).map(path => (
                        <li key={"ssr sequential" + path.id}>
                            {path.id}
                        </li>
                    ))
                }

            </main>
        </div>
    )
}
